export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const CHANGE_ERROR = 'CHANGE_ERROR';

export const LOADING_MB_USER = 'LOADING_MB_USER';
export const CURRENT_MB_USER = 'CURRENT_MB_USER';
export const FAILED_MB_USER = 'FAILED_MB_USER';

export const CURRENT_AMOUNT = 'CURRENT_AMOUNT';
export const CURRENT_BLINKS = 'CURRENT_BLINKS';

export const LOADING_AWS_USER = 'LOADING_AWS_USER';
export const CURRENT_AWS_USER = 'CURRENT_AWS_USER';
export const FAILED_AWS_USER = 'FAILED_AWS_USER';

export const LOADING_AUTH_TYPE = 'LOADING_AUTH_TYPE';
export const AUTH_TYPE = 'AUTH_TYPE';
export const FAILED_AUTH_TYPE = 'FAILED_AUTH_TYPE';

export const LOADING_REGISTER = 'LOADING_REGISTER';
export const REGISTER_AWS = 'REGISTER_AWS';

export const UPDATED_ACCOUNT_INFO = 'UPDATED_ACCOUNT_INFO';

export const LOADING_NOTIFICATIONS = 'LOADING_NOTIFICATIONS';
export const NOTIFICATIONS_LOAD = 'NOTIFICATIONS_LOAD';

export const USER_UPDATE_NOTIFICATIONS = 'USER_UPDATE_NOTIFICATIONS';
