export const en_US = {
    SIGN_IN_HEADER_TEXT: "Custom Sign In Header Text",
    NO_PLAID_PAGE_AVAILABILITY: 'We are having problems to show the platform to integrate your bank accounts.',
    GET_PROFILE_IMAGE: 'Capture profile picture from:',
    GET_CARD_ID_IMAGE: 'Image of identity document:',
    AVATAR_IS_REQUIRED: 'Profile picture is required',
    ADDRESS_IS_REQUIRED: 'Your address is required',
    IDENTIFICATION_IMAGE_IS_REQUIRED: 'The image of your identification is mandatory',
    SELECT_CAMERA: 'Camera',
    SELECT_GALLERY: 'Image Gallery',
    MB_INITIALIZED_TEXT: 'Blink it!',
    PHONE_NUMBER: 'Phone number',
    PHONE_INVALID: 'Phone is invalid',
    PASSWORD_INPUT: 'Enter password',
    EMAIL_INVALID: 'Email is invalid',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    PASSWORD_INVALID: 'The password is invalid. It must contain a distance between 8 and 16 characters. At least one uppercase letter, one lowercase letter, or one symbol "!@#$%^&*".',
    USERNAME_INVALID: 'The username is invalid. It must contain a distance between 4 and 120 characters. At least one lowercase letter, one number, or one symbol ".".',
    FIRST_NAME: 'First name',
    LAST_NAME: 'Family name',
    USERNAME_IS_REQUIRED: 'Username is required',
    PASSWORD_IS_REQUIRED: 'Password is required',
    EMAIL_IS_REQUIRED: 'E-mail is required',
    EMAIL: 'Email',
    SING_IN: 'Sign In',
    SING_UP: 'Sign Up',
    OR: 'Or',
    OF: 'of',
    FORGOT_PASSWORD_TEXT: 'Forgot password?',
    DONT_HAVE_ACCOUNT: 'Don\'t have an account?',
    I_ACCEPT: 'I accept the',
    TERMS_CONDITIONS: 'Terms and Conditions',
    HAVE_ACCOUNT: 'I already have an account.',
    CODE: 'Confirmation code',
    BTN_CONFIRM: 'Confirm',
    RECOVERY: 'Recovery',
    YOU_REMEMBER: 'You already remembered?',
    LOGOUT: 'Logout',
    D_ITEM_HOME: 'Home',
    D_ITEM_ABOUT_US: 'About us',
    D_ITEM_CONTACT_US: 'Contact us',
    D_ITEM_HELP: 'Help',
    D_ITEM_SECURITY: 'Security',
    D_ITEM_SETTINGS: 'Settings',
    D_ITEM_PAYMENT_METHOD: 'Payment methods',
    D_ITEM_ACCOUNT: 'My account',
    BTN_SEND: 'SEND',
    BTN_RECEIVED: 'REQUEST',
    TITLE_SEND_CONTACT: 'My contacts',
    TITLE_SEND_BLINK: 'Send Blink',
    TITLE_CARD_SEND_BLINK: 'How much do you want to send?',
    ERROR_PERMISSION: 'Hey! You have not enabled selected permissions',
    INPUT_SM_PLACEHOLDER: '0.00',
    BLINK_TEXT: 'Blink value',
    VALUE_TO_PAID: 'Amount to be paid',
    "An account with the given phone_number already exists.": 'An account with the given "Phone Number" already exists.',
    "Username/client id combination not found.": "Username not found",
    IDENTIFICATION_NUMBER: 'Identification number',
    BIRTH_DATE: 'Birth date',
    NICKNAME: 'Nickname',
    BTN_OK: 'Accept',
    HEADER_CARD_TITLE: 'Cards',
    HEADER_ACCOUNTS_TITLE: 'Accounts',
    HEADER_ADD_CARD_TITLE: 'Add Card',
    MESSAGE_SHARED_INVITE_1: ' invites you to MoneyBlinks. Use this link',
    MESSAGE_SHARED_INVITE_2: ' to download. Invitation code ',
    PHONE_EXIST: 'The Phone Number already exist',
    EMAIL_EXIST: 'The Email already exist',
    INVALID_PHONE: 'The Phone Number are invalid',
    ZIP_CODE: 'Zip Code',
    ADDRESS: 'Address',
    CITY: 'City',
    STATE: 'State or Province',
    COUNTRY: 'Country',
    NAME_IS_REQUIRED: 'Name is required',
    LAST_NAME_IS_REQUIRED: 'Last Name is required',
    INVALID_CODE: 'The code is required and it must contain a distance of 6 characters',
    INVALID_TX_CODE: 'The code is required and it must contain a distance of 8 characters',
    ZIP_CODE_INVALID: 'The Zip Code is invalid',
    COUNTRY_INVALID: 'The Country is required',
    STATE_INVALID: 'The State/Province is required',
    CITY_INVALID: 'The City is required',
    ADDRESS_INVALID: 'The City is required',
    IDENTIFICATION_NUMBER_INVALID: 'The identification number is required',
    NICKNAME_INVALID: 'The nickname is required',
    NICKNAME_IN_USE: 'The username is in use',
    LOADING_TITLE: 'Loading...',
    LOADING_CONTENT: 'Load data from server.',
    USERNAME_INPUT: 'Username',
    USERNAME_PLACEHOLDER: 'Username',
    EMAIL_IN_USE: 'The email is in use',
    USER_NO_FOUND: 'User not found',
    FULL_NAME: 'Full name',
    COMPLETE_INFORMATION: 'You must complete your account in order to transact. Go to the main menu, option "My Account".',
    SEND_INVITE: 'Invite',
    BUY_PACKAGES: 'Packages',
    REGISTERS: 'Registers',
    AMOUNT: 'Amount',
    REMAIN: 'Remaining',
    USED_BLINK: 'Used Blink',
    HELP_BLINK: '',
    FEDERAL_TAX: 'Federal Tax',
    NJ_TAX: 'New Jersey Tax',
    SUB_TOTAL: 'Total',
    SELECT_CONTACT: 'Send to',
    PAYMENT_METHODS: 'Payment Method',
    EC_TAX: 'Ecuador I.V.A',
    CONTACT_LIST: 'Contacts',
    SHARED: 'Social networks',
    SHARED_TX: ' has sent to ',
    SHARED_TX_PAY: ' with MoneyBlinks. Use this link ',
    SHARED_TX_CODE: ' to download and the code to collect',
    CONTACT_SEND: 'Select a contact from:',
    CONTACT_REQUEST: 'Request Blink to',
    SEARCH_ITEM: 'Search...',
    SEARCH_ERROR: 'Items not found...',
    MESSAGE: 'Message',
    COMPLETED_BTN: 'OK',
    NOTIFY_TO_3RD: 'Notify third parties with:',
    NOTIFY_TO: 'Notify to',
    FULL_LIST: 'You can only notify up to 3 people',
    HEADER_ADD_ACCOUNT_TITLE: 'Add bank account',
    CARD_EXPIRED_TIME: 'The expiration date is incorrect',
    CARD_CVV: 'The cvc is wrong',
    CARD_NAME: 'The name printed on the card is wrong',
    CARD_NUMBER: 'The card number is wrong',
    CARD_NUMBER_INCOMPLETE: 'The card number is incomplete',
    ERROR_METHOD_UNAVAILABILITY: 'This payment method is not available in your region',
    ACCOUNT_NOT_FOUND: 'You do not have bank accounts available to operate',
    LOADING_INFO: 'Processing information...',
    ERROR_LOAD_PLAID: 'At this time we cannot accommodate your request.',
    REFRESH_REQUEST: 'Retry...',
    NO_ITEM_SELECTED: 'Select a payment method',
    PAY_WITH: 'Pay with...',
    AMOUNT_SEND_MIN: 'Does not meet the minimum amount to send',
    AMOUNT_SEND_MAX: 'You do not meet the maximum amount to send',
    AMOUNT_SEND_REQ: 'The amount to send is required',
    TOTAL_REQ: 'The total amount is required',
    PAYMENT_METHOD_REQ: 'The payment method is required',
    PAYMENT_METHOD_USED_REQ: 'You must select the source from which to extract the funds for the shipment.',
    PAYMENT_METHOD_USED_REQ_DEP: 'You must select the source from which to extract the funds for the shipment.',
    USED_BLINK_PAY: 'Total amount paid for: ',
    HELP_PAY_BLINK: 'The more you buy the less you pay',
    BLINK_PRICE_UNIT: 'Price per blink',
    BLINK_PRICE_TOTAL: 'Package total price',
    BLINKS: 'Blink qty',
    PREFER_SUGGEST_ADDRESS: 'Do you want me to suggest the address?',
    ERROR_PLAID_CONNECT: 'We are having trouble getting the Plaid data',
    CARDS_NOT_FOUND: 'You do not have cards available to operate',
    SAVE_ACCOUNT: 'Save Account',
    NO_ITEMS_SELECTED: 'Select one...',
    TITLE_BANK: 'Bank Account',
    TITLE_REMOVE_CONFIRM: 'Confirmation',
    TEXT_REMOVE_CONFIRM: 'Are you sure you want to delete this record?',
    MSG_NOTIFY_REQ: 'The message is required',
    TX_ERROR: 'An error occurred while transaction create',
    TEXT_BLINK_RECEIVED: 'Received',
    TITLE_DOWNLOAD_BLINK: 'Blink download',
    SEND_BLINK_BACK: 'You may lose your changes. Are you sure you want to get out?',
    TITLE_GO_BACK: 'Do you want to return?',
    IM_SURE: 'I\'m sure',
    IM_NOT_SURE: 'I\'m not sure',
    GET_FOUND_ORIGIN: 'Where to get the funds from?',
    GET_VALUES_TO_TRANSFER: 'Amount to transfer, charges and taxes',
    NOTE_DOWNLOAD_BLINK: 'just sent you a Blink of',
    NOTE_DOWNLOAD_BLINK_CONT: 'with the following note:',
    PAYMENT_FORM_SELECTED: 'Select where you want to receive the blink',
    TO_RECEIVED: 'Amount to receive',
    CODE_TO_RECEIVED: 'Please enter the 8-digit code sent via SMS or email',
    METHOD_IN: 'To be paid in',
    DEPOSIT_IN: 'Deposit in',
    CONTACT_LIST_FAVORITES: 'My favourites',
    CONTACT_LIST_FREQUENTS: 'My frequent',
    RECEIVED_BLINK_END_TITLE: 'Request a blink',
    REQUEST_VALUE: 'Amount to ask',
    TEXT_BLINK_REQUEST: 'Requested',
    TEXT_BLINK_REJECT: 'Rejected',
    TITLE_TAB_HISTORICAL: 'Record',
    TITLE_TAB_ACCOUNT: 'Account',
    TITLE_TAB_GRAPH: 'Graphics',
    TITLE_TAB_STATUS: 'Status',
    CHANGE_SEND: 'Sent',
    CHANGE_REQUEST: 'Received',
    MB_ALL_CONTACTS: 'MoneyBlinks Users',
    TITLE_INFO: 'Information',
    TITLE_SEND_REQUEST_BLINK: 'Process Blink Requested',
    TEXT_CONFIRM_CODE: 'Please enter the code sent to your email',
    TEXT_ACCOUNT_CREATE: 'Your account has been created successfully',
    TEXT_RECOVERY_INFO: 'Your password has been updated successfully',
    TEXT_ACCOUNT_UPDATE: 'Your details have been updated correctly. You can go to the start or update your payment methods.',
    NO_FAVORITES_NO_FREQUENTS: 'You have no favorite or frequent contacts. You can use the search at the top',
    HOME: 'Start',
    TEXT_BLINK_USER_RECEIVED: 'has asked you to send him a Blink for the value of',
    NO_ITEM_PAYMENT_SELECTED: 'Select a payment method',
    ACCEPT: 'Accept',
    BTN_IGNORE: 'Ignore',
    BTN_REJECT: 'Reject',
    ARE_YOU_SURE: 'Are you sure you want to perform this operation?',
    YOU_SEND_AMOUNT: 'You are sending your contact',
    TOTAL_TO_PAID: 'and you pay the lowest rate in the market',
    DATA_CONTAIN: 'It is likely that this user is already in MoneyBlinks, to avoid additional steps we suggest you send to that contact',
    PACKAGES_TITLES: 'packages',
    TITLE_PACKAGES: 'Buy packages',
    PACKAGES_ACTIVES: 'Active Packages',
    REST_BLINK: 'Remaining blinks',
    ON_SUBMIT_PAY: 'Buy',
    ERR_NOTIFICATIONS_PERMISSION_DENIED: 'You have not granted the necessary permissions to use our application',
    TERM_AND_CONDITIONS: "I have read and accept the ",
    TERM_AND_CONDITIONS1: "terms and conditions ",
    TERM_AND_CONDITIONS2: "of the MoneyBlinks platform",
    SUPPORT_SUBJECT_CONTACT: 'Contact us',
    PLAID_RETRY: 'Retry',
    PAYMENT_NOTE: 'This payment method is used in case your balance does not cover the full amount.',
    HAVE_CODE: 'Do you have a code?',
    TITLE_REJECTED: 'You have been rejected a blink',
    BODY_REJECTED: ' has rejected the blink you requested by a value of ',
    TITLE_HEADER_LIST_ACCOUNT: 'Account',
    TITLE_HEADER_LIST_STATUS: 'Status',
    TITLE_HEADER_LIST_TX: 'Transactions',
    INSUFFICIENT_FUNDS_ACCOUNT: 'Insufficient funds in your account',
    TITLE_SEND_NOTIFICATION: 'You have been sent a blink',
    BODY_SEND_NOTIFICATION: ' he has send you for a blink for the amount of ',
    TITLE_REQ_NOTIFICATION: 'You have a requested blink',
    BODY_REQ_NOTIFICATION: ' he has asked you for a blink for the amount of ',
    TITLE_RECEIVED_BLINK: 'They have received the sent blink',
    BODY_RECEIVED_BLINK: ' he has received the blink you sent him.',
    INSUFFICIENT_FUNDS: 'Insufficient funds to carry out the operation.',
    LANGUAGE: 'Language',
    SETTINGS_SECURITY_PARAMETERS: 'Configure security settings',
    MFA_ACCEPTED: 'Authentication Multifactor',
    USE_AMOUNT_MB: 'Use MoneyBlinks balance first',
    PROMOTIONAL_ACCEPTED: 'I agree to receive promotional information',
    NO_ACCEPTED_REQUEST_BLINK: 'Do not accept requests for request',
    TEXT_VERSION: 'Version:',
    ALL_RIGHT: 'All rights reserved',
    CODE_TEXT: 'Have you received a MoneyBlinks code? Enter it below and you can receive money more quickly and safely.',
    CODE_TO_RECEIVED_UNK: 'Enter the received code',
    INVALID_TX_CODE_UNK: 'The confirmation code is required and must be 8 alphanumeric characters.',
    DONT_CODE: 'The code entered is not in our system.',
    CODE_IS_USED: 'The code entered has already been used before, please verify and enter a correct code.',
    TITLE_INVITED_ACCEPTED: 'They have accepted an invitation you made to use MoneyBlinks',
    TEXT_INVITED_ACCEPTED: ' has accepted an invitation you made to use MoneyBlinks',
    TEXT_NEW_CONTACT_1: 'You are now a contact of',
    TEXT_NEW_CONTACT_2: 'You can now send and receive blinks safely.',
    TEXT_USER_RECEIVED_BLINK: 'he has received the blink you sent him, he can now pay and confirm the blink.',
    TITLE_USER_RECEIVED_BLINK: 'A user is ready to receive the blink',
    TEXT_YOUR_RECEIVED_BLINK: 'it is sending you a blink for the value of',
    TEXT_YOUR_RECEIVED_BLINK_2: 'once the sender confirms the transaction, you will receive a notification and your money will be available',
    TITLE_SEND_BLINK_CONFIRM: 'Confirmation of sent blink',
    TODAY: 'Today',
    WEEK: 'Week',
    MONTH: 'Month',
    PERIOD_TYPE: 'Specific period',
    MOVEMENTS: 'Movements',
    AMOUNT_TOTAL: 'Balance',
    SELECT_ITEM: 'Select',
    COLLECTIONS_DOWNS: 'Collections made',
    SEND_BLINKS: 'Blinks sent',
    RECEIPTED_BLINKS: 'Blinks received',
    PACKAGES_PAYS: 'Packages purchased',
    CHARGES_PAY: 'Charges paid',
    TAXES_PAY: 'Taxes paid',
    FROM_AT: 'From',
    TO_AT: 'Until',
    CURRENT_STATUS: 'My current status',
    TITLE_NOTIFICATIONS: 'Notifications',
    PHONE_CONTACT: 'Phone',
    MONEY_BLINKS_CONTACTS: 'MoneyBlinks',
    LOAD_CONTACTS: 'Load Contacts',
    CONTACT_SEND_TO: 'Sending blink to:',
    NO_NOTIFICATIONS: 'You have no notifications available',
    POLITICS_TERMS: 'Privacy Policy',
    ERROR_LOAD_USER: 'We are having problems loading user information, please contact us through support@moneyblinks.com',
    USE_ADDRESS: 'Accept Address',
    CANCEL: 'Cancel',
    CAPTURE_IMG_TITLE: 'Continue with',
    CAMERA: 'Camera',
    GALLERY: 'Gallery',
    UPLOAD_IMAGE_ID_FRONT: 'Attach photo of your personal ID',
    BTN_ATTACH: 'Attach',
    ZIP_CODE_IS_REQUIRED: 'The Zip Code is required',
    UPDATE_INFO_USER: 'User information has been updated successfully',
    AN_ERROR_OCCURRED: 'An unexpected error has occurred. Try again later.',
    PAYMENT_METHOD_USED_REQ_INVALID: 'You must select one of the payment methods available for this item',
    NO_PHONE_CONTACTS: 'The search does not return results between your phone contacts.',
    BUY_PACKAGES_SUCCESSFULLY: 'The purchase of your package has been successful. Enjoy MoneyBlinks',
    INVALID_ACCOUNT_ID: 'The selected account does not allow transactions, select another form of payment.',
    "Insufficient founds": "Insufficient funds in the selected payment method",
    NO_HISTORICAL_TX: 'You do not have historical transaction records on our platform',
    CONFIRM_TEXT: 'For your security, prior to proceed charging you payment method, please confirm the transaction.',
    ITEM_LOGIN_REQUIRED: 'Delete your account and try to reconnect through our platform. Sorry for any inconvenience this may cause you.',
    CONFIRM_ID_TX: 'Confirm identity and transfer',
    TRANSFER_TO: 'Confirm Identity:',
    CONFIRM_TX: 'Data confirm:',
    TX_REJECTED: 'You have successfully rejected this blink.',
    CASH_MONEY: 'Balance options',
    CASH_OPTIONS: 'Available options',
    TEXT_CASH_MONEY: 'Manage your money in the outstanding Balance in Moneyblinks. You can send it to your bank account or cash it out anytime.  if you want to increase it you can cash in choosing that option.',
    "Insufficient Params": "Insufficient parameters to carry out this operation, consult our support center at this address: soporte@moneyblinks.com",
    TEXT_DOWN_CASH_MONEY: 'Amount you want to download from the MoneyBlinks balance',
    CODE_TO_RECEIVED_DOWN: 'Use the following code to download the money outside of our platform.',
    IDENTIFICATION_TYPE: 'Identification Type'
};
