export const es_ES = {
    SIGN_IN_HEADER_TEXT: "Custom Sign In Header Text",
    NO_PLAID_PAGE_AVAILABILITY: 'Estamos teniendo problemas para mostrar la plataforma para integrar sus cuentas bancarias.',
    GET_PROFILE_IMAGE: 'Capturar imagen de perfil desde:',
    GET_CARD_ID_IMAGE: 'Imagen de documento de identidad:',
    AVATAR_IS_REQUIRED: 'Se requiere una foto de su perfil',
    ADDRESS_IS_REQUIRED: 'Tu dirección es obligatoria',
    IDENTIFICATION_IMAGE_IS_REQUIRED: 'La imagen de su identificación es obligatoria',
    SELECT_CAMERA: 'Cámara',
    SELECT_GALLERY: 'Galería de imágenes',
    MB_INITIALIZED_TEXT: '¡Asi de simple!',
    PHONE_NUMBER: 'Móvil',
    PASSWORD_INPUT: 'Contraseña',
    PASSWORD_INPUT_RECOVERY: 'Nueva contraseña',
    PHONE_INVALID: 'El teléfono no es válido',
    EMAIL_INVALID: 'El correo electrónico es invalido',
    PASSWORD_PLACEHOLDER: 'Ingresa tu contraseña',
    PASSWORD_PLACEHOLDER_RECOVERY: 'Ingresa tu nueva contraseña',
    PASSWORD_INVALID: 'La contraseña no es válida. Debe contener una distancia entre 8 y 16 caracteres. Al menos una letra mayúscula, una letra minúscula o un símbolo "!@#$%^&*".',
    USERNAME_INVALID: 'El nombre de usuario no es válido. Debe contener una distancia entre 4 y 120 caracteres. Sólo debe contener letras minúsculas, números o ".".',
    FIRST_NAME: 'Nombres',
    LAST_NAME: 'Apellidos',
    EMAIL: 'Correo electrónico',
    USERNAME_IS_REQUIRED: 'El nombre de usuario es obligatorio',
    PASSWORD_IS_REQUIRED: 'La contraseña es obligatoria',
    EMAIL_IS_REQUIRED: 'El correo electrónico es obligatorio',
    SING_IN: 'Entrar',
    SING_UP: 'Registrarse',
    OR: 'O',
    OF: 'de',
    FORGOT_PASSWORD_TEXT: '¿Se te olvidó tu contraseña?',
    DONT_HAVE_ACCOUNT: '¿No tienes una cuenta?',
    I_ACCEPT: 'Acepto los',
    TERMS_CONDITIONS: 'Términos y Condiciones',
    HAVE_ACCOUNT: 'Ya tengo una cuenta.',
    CODE: 'Código de Confirmación',
    BTN_CONFIRM: 'Confirmar',
    RECOVERY: 'Recuperar',
    YOU_REMEMBER: '¿Ya te acordaste?',
    LOGOUT: 'Cerrar sesión',
    D_ITEM_HOME: 'Inicio',
    D_ITEM_ABOUT_US: 'Acerca de',
    D_ITEM_CONTACT_US: 'Contáctenos',
    D_ITEM_HELP: 'Ayuda',
    D_ITEM_SECURITY: 'Seguridad',
    D_ITEM_SETTINGS: 'Configuración',
    D_ITEM_PAYMENT_METHOD: 'Formas de pago',
    D_ITEM_ACCOUNT: 'Mi cuenta',
    BTN_SEND: 'ENVIAR',
    BTN_RECEIVED: 'PEDIR',
    TITLE_SEND_CONTACT: 'Mis contactos',
    TITLE_SEND_BLINK: 'Enviar Blink',
    TITLE_CARD_SEND_BLINK: '¿Cuánto quiere enviar?',
    ERROR_PERMISSION: '¡Oye! No ha habilitado los permisos seleccionados',
    INPUT_SM_PLACEHOLDER: '0.00',
    BLINK_TEXT: 'Valor del blink',
    VALUE_TO_PAID: 'Valor a pagar',
    "An account with the given phone_number already exists.": 'Ya existe una cuenta con ese "Número de Teléfono".',
    "Incorrect username or password.": 'Usuario o contraseña incorrecta.',
    "Password attempts exceeded": "Se superaron los intentos de contraseña",
    "Username should be a phone number.": "El número de teléfono debe ser válido, ej: +19548956165.",
    "User does not exist.": "El usuario no existe.",
    "User already exists": "El usuario ya existe.",
    "Invalid verification code provided, please try again.": "Se proporcionó un código de verificación no válido. Vuelva a intentarlo.",
    "User cannot be confirmed. Current status is CONFIRMED": "El usuario no necesita confirmación.",
    "Terms and conditions must be accepted.": "Debe aceptar los términos y condiciones.",
    "User is not confirmed.": "El usuario no ha sido confirmado.",
    IDENTIFICATION_NUMBER: 'Número de Identificación',
    BIRTH_DATE: 'Fecha de Nacimiento',
    NICKNAME: 'Nickname',
    BTN_OK: 'Aceptar',
    HEADER_CARD_TITLE: 'Tarjetas',
    HEADER_ACCOUNTS_TITLE: 'Cuentas',
    HEADER_ADD_CARD_TITLE: 'Agregar Tarjeta',
    MESSAGE_SHARED_INVITE_1: ' le invita a MoneyBlinks, use este Link ',
    MESSAGE_SHARED_INVITE_2: ' para descargar. Código de invitación ',
    PHONE_EXIST: 'El número de teléfono ya existe',
    EMAIL_EXIST: 'El correo electrónico ya existe',
    INVALID_PHONE: 'El número de teléfono no es válido',
    ADDRESS: 'Dirección',
    ZIP_CODE: 'Código Postal',
    CITY: 'Ciudad',
    STATE: 'Estado o Provincia',
    COUNTRY: 'País',
    NAME_IS_REQUIRED: 'El nombre es obligatorio',
    LAST_NAME_IS_REQUIRED: 'El apellido es obligatorio',
    INVALID_CODE: 'El código es obligatorio y debe contener una distancia de 6 caracteres',
    INVALID_TX_CODE: 'El código es obligatorio y debe contener una distancia de 8 caracteres',
    "Pending sign-in attempt already in progress": 'Intento de inicio de sesión pendiente ya en curso',
    "Username/client id combination not found.": "Usuario no encontrado",
    ZIP_CODE_INVALID: 'El Código Postal es inválido',
    COUNTRY_INVALID: 'El País es obligatorio',
    STATE_INVALID: 'El Estado/Provincia es obligatorio',
    CITY_INVALID: 'La Ciudad es obligatoria',
    ADDRESS_INVALID: 'La Dirección es obligatoria',
    IDENTIFICATION_NUMBER_INVALID: 'El número de identificación es obligatorio',
    NICKNAME_INVALID: 'El nickname es obligatorio',
    NICKNAME_IN_USE: 'El usuario esta en uso',
    LOADING_TITLE: 'Cargando...',
    LOADING_CONTENT: 'Cargando datos del servidor.',
    USERNAME_INPUT: 'Usuario',
    USERNAME_PLACEHOLDER: 'Usuario',
    EMAIL_IN_USE: 'El correo electrónico esta en uso',
    USER_NO_FOUND: 'Usuario no encontrado',
    FULL_NAME: 'Nombres y Apellidos',
    COMPLETE_INFORMATION: 'Debe completar su cuenta para poder realizar transacciones. Vaya al menú principal, opción "Mi Cuenta".',
    SEND_INVITE: 'Invitar',
    BUY_PACKAGES: 'Paquetes',
    REGISTERS: 'Registros',
    AMOUNT: 'Monto',
    REMAIN: 'Restantes',
    AMOUNT_SEND: 'Monto a enviar',
    USED_BLINK: 'Blink usado',
    HELP_BLINK: 'Este Blink se descuenta del saldo de blinks',
    FEDERAL_TAX: 'Impuesto Federal',
    NJ_TAX: 'Impuesto New Jersey',
    SUB_TOTAL: 'Monto Total',
    SELECT_CONTACT: 'Enviar a',
    PAYMENT_METHODS: 'Método de Pago',
    EC_TAX: 'I.V.A Ecuador',
    CONTACT_LIST: 'Contactos',
    SHARED: 'Redes sociales',
    SHARED_TX: ' le ha enviado ',
    SHARED_TX_PAY: ' con MoneyBlinks. Use este link ',
    SHARED_TX_CODE: ' para instalar y para recibir use este código ',
    SEND_BLINK_END_TITLE: 'Completar envío',
    CONTACT_SEND: 'Seleccione un contacto de:',
    CONTACT_REQUEST: 'Pedir Blink a',
    SEARCH_ITEM: 'Buscar...',
    SEARCH_ERROR: 'Elementos no encontrados...',
    MESSAGE: 'Mensaje',
    COMPLETED_BTN: 'Aceptar',
    NOTIFY_TO_3RD: 'Notificar a terceros con:',
    NOTIFY_TO: 'Notificar a',
    FULL_LIST: 'Usted sólo puede notificar hasta 3 personas',
    HEADER_ADD_ACCOUNT_TITLE: 'Agregar Cuenta',
    CARD_EXPIRED_TIME: 'La fecha de expiración es incorrecta',
    CARD_CVV: 'El cvc es incorrecto',
    CARD_NAME: 'El nombre impreso en la tarjeta es incorrecto',
    CARD_NUMBER: 'El número de la tarjeta es incorrecto',
    ERROR_METHOD_UNAVAILABILITY: 'Esta forma de pago no esta disponible en su región.',
    ACCOUNT_NOT_FOUND: 'No tiene cuentas disponibles para operar',
    LOADING_INFO: 'Procesando la información...',
    TITLE_REMOVE_CONFIRM: 'Confirmación',
    TEXT_REMOVE_CONFIRM: '¿Está seguro de que desea eliminar este registro?',
    ERROR_LOAD_PLAID: 'En estos momentos no podemos atender su solicitud.',
    REFRESH_REQUEST: 'Reintentar...',
    NO_ITEM_SELECTED: 'Seleccione una forma de pago',
    PAY_WITH: 'Pagar con...',
    AMOUNT_SEND_MIN: 'No cumple con el monto mínimo a enviar',
    AMOUNT_SEND_MAX: 'No cumple con el monto máximo a enviar',
    AMOUNT_SEND_REQ: 'El monto a enviar es obligatorio',
    TOTAL_REQ: 'El monto a enviar es obligatorio',
    PAYMENT_METHOD_REQ: 'El método de pago es obligatorio',
    PAYMENT_METHOD_USED_REQ: 'Debe seleccionar el origen desde donde extraer los fondos para el envío.',
    PAYMENT_METHOD_USED_REQ_DEP: 'You must select where to deposit the funds for the shipment.',
    USED_BLINK_PAY: 'Monto total pagado por: ',
    HELP_PAY_BLINK: 'Cuanto más compra menos paga',
    BLINK_PRICE_UNIT: 'Valor por blink',
    BLINK_PRICE_TOTAL: 'Valor del paquete',
    BLINKS: 'Cantidad de Blinks',
    PREFER_SUGGEST_ADDRESS: '¿Quieres que te sugiera la dirección?',
    ERROR_PLAID_CONNECT: 'Estamos presentando problemas para obtener los datos de Plaid',
    CARDS_NOT_FOUND: 'No tiene tarjetas disponibles para operar',
    SAVE_ACCOUNT: 'Guardar cuenta',
    NO_ITEMS_SELECTED: 'Seleccione...',
    TITLE_BANK: 'Cuenta bancaria',
    MSG_NOTIFY_REQ: 'El mensaje es obligatorio',
    TX_ERROR: 'Ha ocurrido un error mientras se creaba la transacción',
    TEXT_BLINK_RECEIVED: 'Recibidos',
    TITLE_DOWNLOAD_BLINK: 'Descargar el blink',
    NOTE_DOWNLOAD_BLINK: 'acaba de enviarte un Blink de',
    NOTE_DOWNLOAD_BLINK_CONT: 'con la siguiente nota:',
    PAYMENT_FORM_SELECTED: 'Seleccione dónde desea recibir el blink',
    TO_RECEIVED: 'Monto a recibir',
    CODE_TO_RECEIVED: 'Por favor ingresa el código de 8 dígitos enviado vía SMS o correo electrónico',
    METHOD_IN: 'A cobrar en',
    DEPOSIT_IN: 'Deposito en',
    CONTACT_LIST_FAVORITES: 'Mis Favoritos',
    CONTACT_LIST_FREQUENTS: 'Mis frecuentes',
    RECEIVED_BLINK_END_TITLE: 'Pedir un blink',
    REQUEST_VALUE: 'Monto a pedir',
    TEXT_BLINK_REQUEST: 'Pedido',
    TEXT_BLINK_REJECT: 'Rechazado',
    TITLE_TAB_HISTORICAL: 'Historial',
    TITLE_TAB_ACCOUNT: 'Cuenta',
    TITLE_TAB_GRAPH: 'Graficos',
    TITLE_TAB_STATUS: 'Estatus',
    CHANGE_SEND: 'Enviados',
    CHANGE_REQUEST: 'Recibidos',
    MB_ALL_CONTACTS: 'Usuarios de MoneyBlinks',
    TITLE_INFO: 'Información',
    TITLE_SEND_REQUEST_BLINK: 'Procesar Blink Pedido',
    TEXT_CONFIRM_CODE: 'Por favor ingrese el código enviado a su correo electrónico',
    TEXT_ACCOUNT_CREATE: 'Su cuenta ha sido creada exitosamente',
    TEXT_RECOVERY_INFO: 'Su contraseña se ha actualizado correctamente',
    TEXT_ACCOUNT_UPDATE: 'Sus datos han sido actualizados correctamente. Puede ir al inicio o actualizar sus metodos de pago.',
    NO_FAVORITES_NO_FREQUENTS: 'No dispone de contactos favoritos ni frecuentes. Puede utilizar la busqueda en su parte superior',
    HOME: 'Inicio',
    TEXT_BLINK_USER_RECEIVED: 'te ha solicitado que le envies un Blink por el valor de',
    NO_ITEM_PAYMENT_SELECTED: 'Seleccione un metodo de pago',
    ACCEPT: 'Aceptar',
    BTN_IGNORE: 'Ignorar',
    BTN_REJECT: 'Rechazar',
    ARE_YOU_SURE: '¿Estas seguro de que deseas realizar esta operacion?',
    SEND_BLINK_BACK: 'Puede perder sus cambios. ¿Seguro que quieres salir?',
    TITLE_GO_BACK: '¿Quieres volver?',
    IM_SURE: 'Estoy seguro',
    IM_NOT_SURE: 'No estoy seguro',
    GET_FOUND_ORIGIN: '¿De dónde sacar los fondos?',
    GET_VALUES_TO_TRANSFER: 'Valor a transferir, cargos e impuestos',
    YOU_SEND_AMOUNT: 'Le estas enviando a tu contacto',
    TOTAL_TO_PAID: 'y pagas la tarifa mas baja del mercado',
    DATA_CONTAIN: 'Es probable que este usuario ya este en MoneyBlinks, para evitar pasos adicionales te sugerimos que hagas el envio a ese contacto',
    PACKAGES_TITLES: 'Paquetes',
    TITLE_PACKAGES: 'Comprar paquetes',
    PACKAGES_ACTIVES: 'Paquetes Activos',
    REST_BLINK: 'Blinks restantes',
    ON_SUBMIT_PAY: 'Comprar',
    ERR_NOTIFICATIONS_PERMISSION_DENIED: 'No ha concedido los permisos necesarios para poder usar nuestra aplicación',
    TERM_AND_CONDITIONS: "He leído y acepto los ",
    TERM_AND_CONDITIONS1: "términos y condiciones ",
    TERM_AND_CONDITIONS2: "de la plataforma MoneyBlinks",
    SUPPORT_SUBJECT_CONTACT: 'Contacta con nosotros',
    PLAID_RETRY: 'Reintentar',
    PAYMENT_NOTE: 'Este método de pago se utiliza en caso de que su saldo no cubra el monto total.',
    HAVE_CODE: '¿Tienes un código?',
    TITLE_REQ_NOTIFICATION: 'Tienes un blink solicitado',
    BODY_REQ_NOTIFICATION: ' te ha pedido un blink por la cantidad de ',
    TITLE_REJECTED: 'Te han rechazado un blink',
    BODY_REJECTED: ' ha rechazado el blink que solicitaste por un valor de ',
    TITLE_HEADER_LIST_ACCOUNT: 'Cuenta',
    TITLE_HEADER_LIST_STATUS: 'Status',
    TITLE_HEADER_LIST_TX: 'Registros',
    INSUFFICIENT_FUNDS_ACCOUNT: 'Fondos insuficientes en su cuenta',
    TITLE_SEND_NOTIFICATION: 'Te han enviado un blink',
    BODY_SEND_NOTIFICATION: ' te ha enviado un blink por la cantidad de ',
    TITLE_RECEIVED_BLINK: 'Han recibido el blink enviado',
    BODY_RECEIVED_BLINK: ' ha recibido el blink que le has enviado.',
    INSUFFICIENT_FUNDS: 'Fondos insuficientes para realizar la operación.',
    LANGUAGE: 'Idioma',
    SETTINGS_SECURITY_PARAMETERS: 'Configurar parámetros de seguridad',
    MFA_ACCEPTED: 'Multifactor de Autenticación',
    USE_AMOUNT_MB: 'Usar primero el saldo de MoneyBlinks',
    PROMOTIONAL_ACCEPTED: 'Acepto recibir información promocional',
    NO_ACCEPTED_REQUEST_BLINK: 'No acepte solicitudes de pedidos',
    TEXT_VERSION: 'Versión:',
    ALL_RIGHT: 'Todos los derechos reservados',
    CODE_TEXT: '¿Ha recibido un código MoneyBlinks? Ingréselo a continuación y podrá recibir dinero de forma más rápida y segura.',
    CODE_TO_RECEIVED_UNK: 'Ingresa el código recibido',
    INVALID_TX_CODE_UNK: 'El código de confirmación es requerido y debe tener 8 caracteres alfanuméricos.',
    CODE_IS_USED: 'El código ingresado ya se ha utilizado antes, verifique e ingrese un código correcto.',
    DONT_CODE: 'El código ingresado no esta en nuestro sistema.',
    TITLE_INVITED_ACCEPTED: 'Han aceptado una invitación que realizaste a usar MoneyBlinks',
    TEXT_INVITED_ACCEPTED: ' ha aceptado una invitación que realizaste a usar MoneyBlinks',
    TEXT_NEW_CONTACT_1: 'Ahora eres contacto de',
    TEXT_NEW_CONTACT_2: 'Ya puedes enviar y recibir blinks de forma segura.',
    TEXT_USER_RECEIVED_BLINK: 'ha recibido el blink que le enviaste, ya puede pagar y confirmar el blink.',
    TITLE_USER_RECEIVED_BLINK: 'Un usuario esta listo para recibir el blink',
    TEXT_YOUR_RECEIVED_BLINK: 'le esta enviando un blink por el valor de',
    TEXT_YOUR_RECEIVED_BLINK_2: 'una vez que el remitente le confirme la trasacción, recibiras una notificación y tu dinero estará disponible',
    TITLE_SEND_BLINK_CONFIRM: 'Confirmación del blink enviado',
    TODAY: 'Hoy',
    WEEK: 'Semana',
    MONTH: 'Mes',
    PERIOD_TYPE: 'Período específico',
    MOVEMENTS: 'Movimientos',
    AMOUNT_TOTAL: 'Saldo',
    SELECT_ITEM: 'Seleccione',
    COLLECTIONS_DOWNS: 'Cobros realizados',
    SEND_BLINKS: 'Blinks enviados',
    RECEIPTED_BLINKS: 'Blinks recibidos',
    PACKAGES_PAYS: 'Paquetes adquiridos',
    CHARGES_PAY: 'Cargos pagados',
    TAXES_PAY: 'Impuestos pagados',
    FROM_AT: 'Desde',
    TO_AT: 'Hasta',
    CURRENT_STATUS: 'Mi estatus actual',
    STATUS: 'Estatus',
    POINTS_REQUIRED: 'Puntos requeridos',
    LEVEL: 'Nivel',
    DOWNLOADS: 'Descargas',
    USES: 'Usos',
    POINTS: 'Puntos',
    TITLE_NOTIFICATIONS: 'Notificaciones',
    PHONE_CONTACT: 'Teléfono',
    MONEY_BLINKS_CONTACTS: 'MoneyBlinks',
    LOAD_CONTACTS: 'Cargando contactos',
    CONTACT_SEND_TO: 'Enviando blink a:',
    NO_NOTIFICATIONS: 'No tiene notificaciones disponibles',
    POLITICS_TERMS: 'Política de Privacidad',
    ERROR_LOAD_USER: 'Estamos presentando problemas para cargar la información de usuario, póngase en contacto con nosotros a traves de soporte@moneyblinks.com',
    USE_ADDRESS: 'Aceptar Dirección',
    CANCEL: 'Cancelar',
    CAPTURE_IMG_TITLE: 'Continuar con',
    CAMERA: 'Cámara',
    GALLERY: 'Galería',
    UPLOAD_IMAGE_ID_FRONT: 'Adjunte foto de su Identificación personal',
    BTN_ATTACH: 'Adjuntar',
    ZIP_CODE_IS_REQUIRED: 'El Código Postal es obligatorio',
    UPDATE_INFO_USER: 'La información del usuario se ha actualizado correctamente',
    AN_ERROR_OCCURRED: 'Ha ocurrido un error inesperado. Intente más tarde.',
    PAYMENT_METHOD_USED_REQ_INVALID: 'Debe seleccionar una de las formas de pago disponibles para este elemento',
    NO_PHONE_CONTACTS: 'La búsqueda no devuelve resultados entre los contactos de su teléfono',
    BUY_PACKAGES_SUCCESSFULLY: 'La compra de su paquete se ha realizado correctamente. Disfrute MoneyBlinks',
    INVALID_ACCOUNT_ID: 'La cuenta seleccionada no permite realizar transacciones, seleccione otra forma de pago.',
    "Insufficient founds": "Fondos insuficientes en la forma de pago seleccionada",
    NO_HISTORICAL_TX: 'No tiene registros históricos de transacciones en nuestra plataforma',
    "Your user is not authorized to carry out transactions.": "Su usuario no está autorizado para realizar transacciones. No se ha completado el chequeo de su cuenta.",
    CONFIRM_TEXT: 'Por su seguridad, antes de hacer el cargo correspondiente, por favor confirme la transacción.',
    ITEM_LOGIN_REQUIRED: 'Borre su cuenta e intente reconectarla a través de nuestra plataforma. Disculpe las molestias que esto les pueda ocasionar.',
    "The code you provide is not available in our system.": "El código que proporcionas no está disponible en nuestro sistema.",
    CONFIRM_ID_TX: 'Confirmar identidad y la transferencia',
    TRANSFER_TO: 'Confirmar Identidad:',
    CONFIRM_TX: 'Confirmar datos:',
    TX_REJECTED: 'Has rechazado este blink, satisfactoriamente.',
    CASH_MONEY: 'Gestión de saldos',
    CASH_OPTIONS: 'Opciones disponibles',
    CASH_REGISTERS: 'Balance de saldo',
    UP_CASH_AMOUNT: 'Cargar saldo MoneyBlinks',
    DOWN_CASH_AMOUNT: 'Descargar saldo MoneyBlinks',
    PAY_CASH_AMOUNT: 'Pagar con saldo MoneyBlinks',
    UP_CASH_MONEY: 'Cargar saldo',
    DOWN_CASH_MONEY: 'Descargar saldo',
    TEXT_CASH_MONEY: 'Selecciona que deseas hacer con tu dinero en tu Saldo de Moneyblinks. Puedes hacerlo efectivo en cualquier momento enviándolo a tu cuenta Bancaria o cobrar en efectivo. Si deseas cargar dinero a tu saldo puedes hacerlo escogiendo la opción correspondiente.',
    TEXT_UP_CASH_MONEY: 'Nuestra plataforma brinda la posibilidad de realizar cargas de saldo en efectivo, para realizar dicha operación seleccione uno de los locales que le aparecen a continuación y que se encuentran identificados con nuestro logo. Con el código que le mostramos a continuación puede realizar la carga del monto deseado.',
    AMOUNT_UP: 'Saldo a cargar',
    MARKER_AVAILABLE: 'Locales disponibles',
    CODE_GENERATE: 'Al momento de realizar el depósito, use este código y entrege el total de la transacción.',
    "Insufficient Params": "Parámetros insuficientes para realizar esta operación, consulte nuestro centro de soporte en esta dirección: soporte@moneyblinks.com",
    TEXT_DOWN_CASH_MONEY: 'Monto que desea descargar del saldo MoneyBlinks',
    CODE_TO_RECEIVED_DOWN: 'Use el siguiente código para descargar el dinero fuera de nuestra plataforma.',
    IDENTIFICATION_TYPE: 'Tipo de Identificación'
};
