export const FINANCIAL_INFO = 'FINANCIAL_INFO';

export const RELOAD_FINANCIAL = 'RELOAD_FINANCIAL';

export const LOADING_SEND_PAYMENT_METHOD = 'LOADING_SEND_PAYMENT_METHOD';
export const SEND_PAYMENT_METHOD = 'SEND_PAYMENT_METHOD';
export const FAILED_SEND_PAYMENT_METHOD = 'FAILED_SEND_PAYMENT_METHOD';

export const LOADING_BLINK_USER_ID = 'LOADING_BLINK_USER_ID';
export const AVAILABILITY_BLINK_USER_ID = 'AVAILABILITY_BLINK_USER_ID';

export const LOADING_BLINK_SETTING_AV = 'LOADING_BLINK_SETTING_AV';
export const CURRENT_BLINKS_SETTINGS = 'CURRENT_BLINKS_SETTINGS';

export const LOADING_FAVORITES_CONTACTS = 'LOADING_FAVORITES_CONTACTS';
export const CURRENT_FAVORITES = 'CURRENT_FAVORITES';

export const LOADING_MB_CONTACTS = 'LOADING_MB_CONTACTS';
export const CURRENT_MB_CONTACTS = 'CURRENT_MB_CONTACTS';

export const LOADING_USERS_PHONE = 'LOADING_USERS_PHONE';
export const CURRENT_USERS_PHONE = 'CURRENT_USERS_PHONE';

export const LOADING_CHARGES_TAX_COUNTRY = 'LOADING_CHARGES_TAX_COUNTRY';
export const CHARGE_TAX_COUNTRY = 'CHARGE_TAX_COUNTRY';

export const HANDLE_NAVIGATE_TO_HOME = 'HANDLE_NAVIGATE_TO_HOME';
export const HANDLE_TX_TYPE = 'HANDLE_TX_TYPE';

export const LOADING_TRANSACTION = 'LOADING_TRANSACTION';
export const HANDLE_TRANSACTION = 'HANDLE_TRANSACTION';
export const FAILED_TRANSACTION = 'FAILED_TRANSACTION';

export const LOADING_HISTORICAL_TX = 'LOADING_HISTORICAL_TX';
export const HISTORICAL_TX = 'HISTORICAL_TX';
export const FAILED_HISTORICAL_TX = 'FAILED_HISTORICAL_TX';

export const LOADING_IS_EXIST_CONTAIN_DATA = 'LOADING_IS_EXIST_CONTAIN_DATA';
export const IS_EXIST_CONTAIN_DATA = 'IS_EXIST_CONTAIN_DATA';

export const MOVE_TX = 'MOVE_TX';
