export const CHANGE_IS_BACK = 'CHANGE_IS_BACK';

export const LOADING_PAYMENT_METHOD = 'LOADING_PAYMENT_METHOD';
export const MY_PAYMENTS_METHODS = 'MY_PAYMENTS_METHODS';
export const FAILED_PAYMENT_METHODS = 'FAILED_PAYMENT_METHODS';

export const LOADING_PAYMENTS_COUNTRIES = 'LOADING_PAYMENTS_COUNTRIES';
export const COUNTRY_PAYMENTS = 'COUNTRY_PAYMENTS';
export const FAILED_COUNTRY_PAYMENTS = 'FAILED_COUNTRY_PAYMENTS';
